[profile.default]
src = "src"
out = "out"
libs = ["lib"]
remappings = [
    "ERC4626/=lib/properties/lib/ERC4626/contracts/",
    "chimera/=lib/chimera/src/",
    "ds-test/=lib/chimera/lib/forge-std/lib/ds-test/src/",
    "erc4626-tests/=lib/properties/lib/openzeppelin-contracts/lib/erc4626-tests/",
    "forge-std/=lib/chimera/lib/forge-std/src/",
    "openzeppelin-contracts/=lib/properties/lib/openzeppelin-contracts/",
    "properties/=lib/properties/contracts/",
    "solmate/=lib/properties/lib/solmate/src/",
]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
